language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
notifications:
  email: false
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("AccurateArithmetic"); Pkg.test("AccurateArithmetic"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("AccurateArithmetic")); Pkg.add("Documenter"); using Documenter; include(joinpath("docs", "make.jl"))';
  - julia -e 'cd(Pkg.dir("AccurateArithmetic")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
