name = "AccurateArithmetic"
uuid = "22286c92-06ac-501d-9306-4abd417d9753"
repo = "https://github.com/JuliaMath/AccurateArithmetic.jl.git"
license = "MIT"
version = "0.3.0"
authors = ["Chris Elrod <elrodc@gmail.com>",
           "François Févotte <ff@triscale-innov.com>",
           "Jeffrey Sarnoff <JeffreySarnoff@users.noreply.github.com>"]

[deps]
SIMDPirates = "21efa798-c60a-11e8-04d3-e1a92915a26a"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "LinearAlgebra", "Plots", "Printf", "Statistics", "Test"]
